# Generated by Django 2.2.3 on 2019-07-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='activity',
            field=models.CharField(default='Drink', max_length=255),
            preserve_default=False,
        ),
    ]
