# Generated by Django 2.2.3 on 2019-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_information_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='address',
        ),
        migrations.RemoveField(
            model_name='information',
            name='country',
        ),
        migrations.RemoveField(
            model_name='information',
            name='name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='state',
        ),
        migrations.AddField(
            model_name='information',
            name='status',
            field=models.CharField(default='YOLO', max_length=10),
        ),
    ]
