# Generated by Django 2.2.3 on 2019-07-30 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20190730_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Profile',
        ),
    ]
